# Generated by Django 5.2.7 on 2025-10-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bg_color',
            field=models.CharField(default='#f7f7f8', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
    ]
