# Generated by Django 5.2.7 on 2025-10-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_bg_color_profile_bg_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bg_image',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bg_color',
            field=models.CharField(blank=True, help_text='Es. #RRGGBB', max_length=7, null=True),
        ),
    ]
