# Generated by Django 5.2.7 on 2025-10-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_bg_image_alter_profile_bg_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bg_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
